# Generated by Django 4.1.3 on 2022-11-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelOptions(
            name="profilestatus",
            options={"verbose_name_plural": "ProfileStatus'"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="Profile_Picture/%Y/%m/"
            ),
        ),
    ]
